### ISSUE TITLE
Discuss Removal of PEG Parser

### ISSUE THREAD

**Issue by indiv0** [uiri/SEGIMAP#12]
Post arguments for and against the removal of the PEG parser here.

**Comment by uiri** [comment]
At the moment, by largest argument in favour of removing the PEG parser is that it isn't possible to compile the peg library with the stable release.

**Comment by indiv0** [comment]
I think that removing the PEG parser is the best course of action. What would be the alternative though? I think that [nom](https://github.com/Geal/nom) is a good candidate.

**Comment by indiv0** [comment]
Closed by #18, which replaced PEG with nom.
