### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [uiri/SEGIMAP#19]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

------------

- [x] Add `serde` dependencies
- [x] Replace all instances of `RustcDecodable` and `RustcEncodable` with equivalents in `serde`
- [x] Replace JSON usage
- [x] Remove last `rustc-serialize` statements and dependencies

**Comment by indiv0** [comment]
Not that I can think of. Some work has already gone into this in the latest PRs. Thanks for opening an issue!

**Comment by uiri** [comment]
Hi David,

Thanks for bringing this to our attention. I have edited in a checklist for tracking the migration.
