### ISSUE TITLE
Remove Unstable Features

### ISSUE THREAD

**Issue by indiv0** [uiri/SEGIMAP#4]
One PR #3 gets merged, we'll have the following features enabled, which we'll need to move away from:
- [ ] collections
  - HashMap and other features
  - Might not be feasible to update
- [ ] core
  - New slicing syntax
  - Large update
  - @indiv0 will handle this
- [ ] env
  - No replacement ATM as far as I know
- [ ] int_uint
  - Something related to the PEG parser, might not be on our end
- [x] old_io
  - Large update to move to the IO reform in 1.0.0
- [x] old_path
  - Ties into old_io
- [ ] std_misc
  - Various issues currently in the std
  - Probably no way around them ATM

We also use the features:
- [ ] box_patterns
  - Necessary for [this](https://github.com/indiv0/SEGIMAP/blob/b1f46db6fcc7fb3b1d066a04805d513f4ad610ed/src/session.rs#L475) line
  - TODO: research alternatives
- [ ] plugin
  - Necessary for regex and PEG parser plugins

**Comment by uiri** [comment]
Closing as I believe only box_patterns, plugin, and rustc_private are left and those are necessary. Feel free to re-open if you disagree.
